### ISSUE TITLE
ティッシュペーパーが無い問題

### ISSUE THREAD

**Issue by gin49** [S64/home#5]
## 問題 

現在 [@S64](https://github.com/S64) のお家にティッシュペーパが無く非常に問題のある状態だ。非常に問題のある状態なので問題だと思う。

# 解決方法

何らかの方法で [@S64](https://github.com/S64) のお家にティッシュペーパーを補充すれば良い。
例えば

- [@S64](https://github.com/S64) が買いに行く

- [@S64](https://github.com/S64) がamazonで注文する

- [amazonのウォッシュリスト](https://amzn.to/2SEVQ3X)から誰かが購入してくれるのを待つ

- 誰かに持ってきてもらうように頼む

などの方法が考えられる

**Comment by S64** [comment]
これマジで困ってる

**Comment by S64** [comment]
## 現状どうしているか

トイレットペーパーで代用中。宅内で確認できているだけでも16本、さらにクローゼット内を探せばもうすこしあるはずなので、当分は問題ないという判断。
また、日用品としてポケットティッシュは持っているので、必要ならこれを使うこともできるのではないかと考えている。

ただしこれらは根本解決になっていないので、やはりティッシュペーパーの購入はすべきだろうと考えている。

**Comment by S64** [comment]
> <img width="500" alt="slack_-_shuma" src="https://user-images.githubusercontent.com/3754272/52520898-72014f00-2cb2-11e9-98d9-8c07da3dbfb4.png">

**Comment by S64** [comment]
> ティッシュペーパーやトイレットペーパーの残量を監視して自動で注文するソリューション必要では
> 
> https://twitter.com/tmyk_kym/status/1094220555375435776

> 真面目に自動注文やるなら、保管場所にセンサーつけて、その値をポーリングで取得か、センサーからの割り込みかで注文すれば良さそう
> 
> https://twitter.com/tmyk_kym/status/1094222604817166336

***

> ティッシュ定期購入にして使おうと使うまいと毎回勝手に届くのにするのが一番良さそう
> 
> https://twitter.com/beatdjam/status/1094221946944802816

> なくなったら注文だと結局同じことになる
> 
> https://twitter.com/beatdjam/status/1094221992675336194

***

> これはただのケチケチトークなんですが
> 
> 本当は自動注文にしたいものの、通販での箱ティッシュ購入は大概 スーパーやドラッグストアでのセール時を狙った場合より高くつくのと、ティッシュ使用量は多い月少ない月が安定しないので、いまいちだなって思い今の所やってない
> 
> https://twitter.com/shuma_yoshioka/status/1094225315415519233

> でも現実に起きている ティッシュが無いことでの不便やストレスを考えれば、通販で掛かるコスト分くらい余裕でペイできそう
> https://twitter.com/shuma_yoshioka/status/1094225596509446144

**Comment by S64** [comment]
あきらめて注文を掛けた。

**Comment by S64** [comment]
問題は解決した。
